<?php

namespace AppBundle\Repository;

/**
 * shopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shopRepository extends \Doctrine\ORM\EntityRepository
{
}
